<?php

namespace Modules\Admin\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class TestRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            //
            "title" => 'required|is_positive_integer',
        ];
    }

    public function messages(): array
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'title.is_positive_integer' => '这不是正整数111'
        ];
    }


//    public function failedValidation(Validator $validator): void
//    {
////        dd($validator -> errors() -> messages());
////        parent::failedValidation($validator); // TODO: Change the autogenerated stub
//    }
}
